debug: false
game_loc:
  a:
    x: 512
    y: 320
    z: 512
    world: world
  b:
    x: -512
    y: -64
    z: -512
    world: world
start_loc:
  x: -43
  y: 63
  z: 67
teleport_out_loc:
  x: 1004
  y: 125
  z: 1001
out_of_bounds_time_limit: 20
body_scale: 0.2
game_time: 190
hide_time: 20
prepare_time: 20
# 剩余多少时间，游戏进入终局
end_game_time: 25
game_area_protection: true
db_host: '127.0.0.1'
db_port: 3306
db_user: "root"
db_passwd: "123"
db_database: "inventory_recover"